api: '1.21'
name: SkipNight
version: '1.6'
main: com.vch.skipNight.SkipNight
api-version: '1.21'
commands:
  vote:
    description: Vote to continue or skip night
    usage: /<command> <yes|no>
    aliases: [v]
